// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDddeIMPFylmW6itSIWtso8_kXWiBkbwLY',
    appId: '1:752453260376:web:0de166ccae04a3f1af662d',
    messagingSenderId: '752453260376',
    projectId: 'auction-fdd61',
    authDomain: 'auction-fdd61.firebaseapp.com',
    storageBucket: 'auction-fdd61.appspot.com',
    measurementId: 'G-2F6NN19MZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAium1zhMzwcogy5Nib6XtxpXGZarkuMs8',
    appId: '1:752453260376:android:7441a301b23a4863af662d',
    messagingSenderId: '752453260376',
    projectId: 'auction-fdd61',
    storageBucket: 'auction-fdd61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOYfXJ75SlHaUYXJByKwU9IN1mVrJ3qM',
    appId: '1:752453260376:ios:9b945ad3b6f97f8faf662d',
    messagingSenderId: '752453260376',
    projectId: 'auction-fdd61',
    storageBucket: 'auction-fdd61.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOYfXJ75SlHaUYXJByKwU9IN1mVrJ3qM',
    appId: '1:752453260376:ios:9b945ad3b6f97f8faf662d',
    messagingSenderId: '752453260376',
    projectId: 'auction-fdd61',
    storageBucket: 'auction-fdd61.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDddeIMPFylmW6itSIWtso8_kXWiBkbwLY',
    appId: '1:752453260376:web:032a5eb0a685760daf662d',
    messagingSenderId: '752453260376',
    projectId: 'auction-fdd61',
    authDomain: 'auction-fdd61.firebaseapp.com',
    storageBucket: 'auction-fdd61.appspot.com',
    measurementId: 'G-X8L21T805T',
  );
}
